/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Body2 } from '../models';
import { DomainEngaged } from '../models';
import { EnvironmentSummary } from '../models';
import { ErrorModel } from '../models';
import { HttpsConfiguration } from '../models';
import { HttpsSetConfiguration } from '../models';
import { MultiErrorModel } from '../models';
/**
 * DomainApi - axios parameter creator
 * @export
 */
export const DomainApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add a domain to an environment. If there is no certificate passed in the body, a Let's Encrypt certificate will be generated for this domain
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {string} hostName Host Name
         * @param {Body2} [body] Certificate payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        environmentAddDomain: async (accountId: number, applicationId: number, environmentName: string, hostName: string, body?: Body2, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling environmentAddDomain.');
            }
            // verify required parameter 'applicationId' is not null or undefined
            if (applicationId === null || applicationId === undefined) {
                throw new RequiredError('applicationId','Required parameter applicationId was null or undefined when calling environmentAddDomain.');
            }
            // verify required parameter 'environmentName' is not null or undefined
            if (environmentName === null || environmentName === undefined) {
                throw new RequiredError('environmentName','Required parameter environmentName was null or undefined when calling environmentAddDomain.');
            }
            // verify required parameter 'hostName' is not null or undefined
            if (hostName === null || hostName === undefined) {
                throw new RequiredError('hostName','Required parameter hostName was null or undefined when calling environmentAddDomain.');
            }
            const localVarPath = `/account/{accountId}/application/{applicationId}/environment/{environmentName}/domain/{hostName}`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"applicationId"}}`, encodeURIComponent(String(applicationId)))
                .replace(`{${"environmentName"}}`, encodeURIComponent(String(environmentName)))
                .replace(`{${"hostName"}}`, encodeURIComponent(String(hostName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a domain from an environment. Will also remove any certificate linked to the domain
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        environmentRemoveDomain: async (accountId: number, applicationId: number, environmentName: string, hostName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling environmentRemoveDomain.');
            }
            // verify required parameter 'applicationId' is not null or undefined
            if (applicationId === null || applicationId === undefined) {
                throw new RequiredError('applicationId','Required parameter applicationId was null or undefined when calling environmentRemoveDomain.');
            }
            // verify required parameter 'environmentName' is not null or undefined
            if (environmentName === null || environmentName === undefined) {
                throw new RequiredError('environmentName','Required parameter environmentName was null or undefined when calling environmentRemoveDomain.');
            }
            // verify required parameter 'hostName' is not null or undefined
            if (hostName === null || hostName === undefined) {
                throw new RequiredError('hostName','Required parameter hostName was null or undefined when calling environmentRemoveDomain.');
            }
            const localVarPath = `/account/{accountId}/application/{applicationId}/environment/{environmentName}/domain/{hostName}`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"applicationId"}}`, encodeURIComponent(String(applicationId)))
                .replace(`{${"environmentName"}}`, encodeURIComponent(String(environmentName)))
                .replace(`{${"hostName"}}`, encodeURIComponent(String(hostName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get https configuration
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConfiguration: async (accountId: number, hostName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling getConfiguration.');
            }
            // verify required parameter 'hostName' is not null or undefined
            if (hostName === null || hostName === undefined) {
                throw new RequiredError('hostName','Required parameter hostName was null or undefined when calling getConfiguration.');
            }
            const localVarPath = `/account/{accountId}/domain/{hostName}/https`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"hostName"}}`, encodeURIComponent(String(hostName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Set https configuration
         * @param {HttpsSetConfiguration} body Https Set Configuration Payload
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postConfiguration: async (body: HttpsSetConfiguration, accountId: number, hostName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postConfiguration.');
            }
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling postConfiguration.');
            }
            // verify required parameter 'hostName' is not null or undefined
            if (hostName === null || hostName === undefined) {
                throw new RequiredError('hostName','Required parameter hostName was null or undefined when calling postConfiguration.');
            }
            const localVarPath = `/account/{accountId}/domain/{hostName}/https`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"hostName"}}`, encodeURIComponent(String(hostName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Renew certificate
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renewCertificate: async (accountId: number, hostName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling renewCertificate.');
            }
            // verify required parameter 'hostName' is not null or undefined
            if (hostName === null || hostName === undefined) {
                throw new RequiredError('hostName','Required parameter hostName was null or undefined when calling renewCertificate.');
            }
            const localVarPath = `/account/{accountId}/domain/{hostName}/renewCertificate`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"hostName"}}`, encodeURIComponent(String(hostName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Checks if domain is configured to route traffic
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEngaged: async (accountId: number, hostName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling verifyEngaged.');
            }
            // verify required parameter 'hostName' is not null or undefined
            if (hostName === null || hostName === undefined) {
                throw new RequiredError('hostName','Required parameter hostName was null or undefined when calling verifyEngaged.');
            }
            const localVarPath = `/account/{accountId}/domain/{hostName}/verifyEngaged`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"hostName"}}`, encodeURIComponent(String(hostName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DomainApi - functional programming interface
 * @export
 */
export const DomainApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Add a domain to an environment. If there is no certificate passed in the body, a Let's Encrypt certificate will be generated for this domain
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {string} hostName Host Name
         * @param {Body2} [body] Certificate payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async environmentAddDomain(accountId: number, applicationId: number, environmentName: string, hostName: string, body?: Body2, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnvironmentSummary>> {
            const localVarAxiosArgs = await DomainApiAxiosParamCreator(configuration).environmentAddDomain(accountId, applicationId, environmentName, hostName, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Remove a domain from an environment. Will also remove any certificate linked to the domain
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async environmentRemoveDomain(accountId: number, applicationId: number, environmentName: string, hostName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnvironmentSummary>> {
            const localVarAxiosArgs = await DomainApiAxiosParamCreator(configuration).environmentRemoveDomain(accountId, applicationId, environmentName, hostName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get https configuration
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConfiguration(accountId: number, hostName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HttpsConfiguration>> {
            const localVarAxiosArgs = await DomainApiAxiosParamCreator(configuration).getConfiguration(accountId, hostName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Set https configuration
         * @param {HttpsSetConfiguration} body Https Set Configuration Payload
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postConfiguration(body: HttpsSetConfiguration, accountId: number, hostName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HttpsConfiguration>> {
            const localVarAxiosArgs = await DomainApiAxiosParamCreator(configuration).postConfiguration(body, accountId, hostName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Renew certificate
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renewCertificate(accountId: number, hostName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await DomainApiAxiosParamCreator(configuration).renewCertificate(accountId, hostName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Checks if domain is configured to route traffic
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyEngaged(accountId: number, hostName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DomainEngaged>> {
            const localVarAxiosArgs = await DomainApiAxiosParamCreator(configuration).verifyEngaged(accountId, hostName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DomainApi - factory interface
 * @export
 */
export const DomainApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Add a domain to an environment. If there is no certificate passed in the body, a Let's Encrypt certificate will be generated for this domain
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {string} hostName Host Name
         * @param {Body2} [body] Certificate payload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        environmentAddDomain(accountId: number, applicationId: number, environmentName: string, hostName: string, body?: Body2, options?: any): AxiosPromise<EnvironmentSummary> {
            return DomainApiFp(configuration).environmentAddDomain(accountId, applicationId, environmentName, hostName, body, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a domain from an environment. Will also remove any certificate linked to the domain
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        environmentRemoveDomain(accountId: number, applicationId: number, environmentName: string, hostName: string, options?: any): AxiosPromise<EnvironmentSummary> {
            return DomainApiFp(configuration).environmentRemoveDomain(accountId, applicationId, environmentName, hostName, options).then((request) => request(axios, basePath));
        },
        /**
         * Get https configuration
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConfiguration(accountId: number, hostName: string, options?: any): AxiosPromise<HttpsConfiguration> {
            return DomainApiFp(configuration).getConfiguration(accountId, hostName, options).then((request) => request(axios, basePath));
        },
        /**
         * Set https configuration
         * @param {HttpsSetConfiguration} body Https Set Configuration Payload
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postConfiguration(body: HttpsSetConfiguration, accountId: number, hostName: string, options?: any): AxiosPromise<HttpsConfiguration> {
            return DomainApiFp(configuration).postConfiguration(body, accountId, hostName, options).then((request) => request(axios, basePath));
        },
        /**
         * Renew certificate
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renewCertificate(accountId: number, hostName: string, options?: any): AxiosPromise<any> {
            return DomainApiFp(configuration).renewCertificate(accountId, hostName, options).then((request) => request(axios, basePath));
        },
        /**
         * Checks if domain is configured to route traffic
         * @param {number} accountId The account identifier number
         * @param {string} hostName Host Name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEngaged(accountId: number, hostName: string, options?: any): AxiosPromise<DomainEngaged> {
            return DomainApiFp(configuration).verifyEngaged(accountId, hostName, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DomainApi - object-oriented interface
 * @export
 * @class DomainApi
 * @extends {BaseAPI}
 */
export class DomainApi extends BaseAPI {
    /**
     * Add a domain to an environment. If there is no certificate passed in the body, a Let's Encrypt certificate will be generated for this domain
     * @param {number} accountId The account identifier number
     * @param {number} applicationId The application identifier number
     * @param {string} environmentName The name of the environment
     * @param {string} hostName Host Name
     * @param {Body2} [body] Certificate payload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainApi
     */
    public environmentAddDomain(accountId: number, applicationId: number, environmentName: string, hostName: string, body?: Body2, options?: any) {
        return DomainApiFp(this.configuration).environmentAddDomain(accountId, applicationId, environmentName, hostName, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Remove a domain from an environment. Will also remove any certificate linked to the domain
     * @param {number} accountId The account identifier number
     * @param {number} applicationId The application identifier number
     * @param {string} environmentName The name of the environment
     * @param {string} hostName Host Name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainApi
     */
    public environmentRemoveDomain(accountId: number, applicationId: number, environmentName: string, hostName: string, options?: any) {
        return DomainApiFp(this.configuration).environmentRemoveDomain(accountId, applicationId, environmentName, hostName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get https configuration
     * @param {number} accountId The account identifier number
     * @param {string} hostName Host Name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainApi
     */
    public getConfiguration(accountId: number, hostName: string, options?: any) {
        return DomainApiFp(this.configuration).getConfiguration(accountId, hostName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Set https configuration
     * @param {HttpsSetConfiguration} body Https Set Configuration Payload
     * @param {number} accountId The account identifier number
     * @param {string} hostName Host Name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainApi
     */
    public postConfiguration(body: HttpsSetConfiguration, accountId: number, hostName: string, options?: any) {
        return DomainApiFp(this.configuration).postConfiguration(body, accountId, hostName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Renew certificate
     * @param {number} accountId The account identifier number
     * @param {string} hostName Host Name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainApi
     */
    public renewCertificate(accountId: number, hostName: string, options?: any) {
        return DomainApiFp(this.configuration).renewCertificate(accountId, hostName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Checks if domain is configured to route traffic
     * @param {number} accountId The account identifier number
     * @param {string} hostName Host Name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DomainApi
     */
    public verifyEngaged(accountId: number, hostName: string, options?: any) {
        return DomainApiFp(this.configuration).verifyEngaged(accountId, hostName, options).then((request) => request(this.axios, this.basePath));
    }
}
