/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { MultiErrorModel } from '../models';
import { SyntheticTest } from '../models';
/**
 * SyntheticsApi - axios parameter creator
 * @export
 */
export const SyntheticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add a synthetics test
         * @param {SyntheticTest} body Test to add
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTest: async (body: SyntheticTest, accountId: number, applicationId: number, environmentName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling addTest.');
            }
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling addTest.');
            }
            // verify required parameter 'applicationId' is not null or undefined
            if (applicationId === null || applicationId === undefined) {
                throw new RequiredError('applicationId','Required parameter applicationId was null or undefined when calling addTest.');
            }
            // verify required parameter 'environmentName' is not null or undefined
            if (environmentName === null || environmentName === undefined) {
                throw new RequiredError('environmentName','Required parameter environmentName was null or undefined when calling addTest.');
            }
            const localVarPath = `/account/{accountId}/application/{applicationId}/environment/{environmentName}/synthetics`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"applicationId"}}`, encodeURIComponent(String(applicationId)))
                .replace(`{${"environmentName"}}`, encodeURIComponent(String(environmentName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a synthetics test
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {number} testId ID of the test to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTest: async (accountId: number, applicationId: number, environmentName: string, testId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling deleteTest.');
            }
            // verify required parameter 'applicationId' is not null or undefined
            if (applicationId === null || applicationId === undefined) {
                throw new RequiredError('applicationId','Required parameter applicationId was null or undefined when calling deleteTest.');
            }
            // verify required parameter 'environmentName' is not null or undefined
            if (environmentName === null || environmentName === undefined) {
                throw new RequiredError('environmentName','Required parameter environmentName was null or undefined when calling deleteTest.');
            }
            // verify required parameter 'testId' is not null or undefined
            if (testId === null || testId === undefined) {
                throw new RequiredError('testId','Required parameter testId was null or undefined when calling deleteTest.');
            }
            const localVarPath = `/account/{accountId}/application/{applicationId}/environment/{environmentName}/synthetics/{testId}`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"applicationId"}}`, encodeURIComponent(String(applicationId)))
                .replace(`{${"environmentName"}}`, encodeURIComponent(String(environmentName)))
                .replace(`{${"testId"}}`, encodeURIComponent(String(testId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Return all synthetics tests for an environment
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTests: async (accountId: number, applicationId: number, environmentName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            if (accountId === null || accountId === undefined) {
                throw new RequiredError('accountId','Required parameter accountId was null or undefined when calling getTests.');
            }
            // verify required parameter 'applicationId' is not null or undefined
            if (applicationId === null || applicationId === undefined) {
                throw new RequiredError('applicationId','Required parameter applicationId was null or undefined when calling getTests.');
            }
            // verify required parameter 'environmentName' is not null or undefined
            if (environmentName === null || environmentName === undefined) {
                throw new RequiredError('environmentName','Required parameter environmentName was null or undefined when calling getTests.');
            }
            const localVarPath = `/account/{accountId}/application/{applicationId}/environment/{environmentName}/synthetics`
                .replace(`{${"accountId"}}`, encodeURIComponent(String(accountId)))
                .replace(`{${"applicationId"}}`, encodeURIComponent(String(applicationId)))
                .replace(`{${"environmentName"}}`, encodeURIComponent(String(environmentName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            // authentication keyInQuery required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("access_token")
                    : await configuration.apiKey;
                localVarQueryParameter["access_token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SyntheticsApi - functional programming interface
 * @export
 */
export const SyntheticsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Add a synthetics test
         * @param {SyntheticTest} body Test to add
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTest(body: SyntheticTest, accountId: number, applicationId: number, environmentName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SyntheticTest>>> {
            const localVarAxiosArgs = await SyntheticsApiAxiosParamCreator(configuration).addTest(body, accountId, applicationId, environmentName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Deletes a synthetics test
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {number} testId ID of the test to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTest(accountId: number, applicationId: number, environmentName: string, testId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SyntheticTest>>> {
            const localVarAxiosArgs = await SyntheticsApiAxiosParamCreator(configuration).deleteTest(accountId, applicationId, environmentName, testId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Return all synthetics tests for an environment
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTests(accountId: number, applicationId: number, environmentName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SyntheticTest>>> {
            const localVarAxiosArgs = await SyntheticsApiAxiosParamCreator(configuration).getTests(accountId, applicationId, environmentName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SyntheticsApi - factory interface
 * @export
 */
export const SyntheticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Add a synthetics test
         * @param {SyntheticTest} body Test to add
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTest(body: SyntheticTest, accountId: number, applicationId: number, environmentName: string, options?: any): AxiosPromise<Array<SyntheticTest>> {
            return SyntheticsApiFp(configuration).addTest(body, accountId, applicationId, environmentName, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a synthetics test
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {number} testId ID of the test to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTest(accountId: number, applicationId: number, environmentName: string, testId: number, options?: any): AxiosPromise<Array<SyntheticTest>> {
            return SyntheticsApiFp(configuration).deleteTest(accountId, applicationId, environmentName, testId, options).then((request) => request(axios, basePath));
        },
        /**
         * Return all synthetics tests for an environment
         * @param {number} accountId The account identifier number
         * @param {number} applicationId The application identifier number
         * @param {string} environmentName The name of the environment
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTests(accountId: number, applicationId: number, environmentName: string, options?: any): AxiosPromise<Array<SyntheticTest>> {
            return SyntheticsApiFp(configuration).getTests(accountId, applicationId, environmentName, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SyntheticsApi - object-oriented interface
 * @export
 * @class SyntheticsApi
 * @extends {BaseAPI}
 */
export class SyntheticsApi extends BaseAPI {
    /**
     * Add a synthetics test
     * @param {SyntheticTest} body Test to add
     * @param {number} accountId The account identifier number
     * @param {number} applicationId The application identifier number
     * @param {string} environmentName The name of the environment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyntheticsApi
     */
    public addTest(body: SyntheticTest, accountId: number, applicationId: number, environmentName: string, options?: any) {
        return SyntheticsApiFp(this.configuration).addTest(body, accountId, applicationId, environmentName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Deletes a synthetics test
     * @param {number} accountId The account identifier number
     * @param {number} applicationId The application identifier number
     * @param {string} environmentName The name of the environment
     * @param {number} testId ID of the test to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyntheticsApi
     */
    public deleteTest(accountId: number, applicationId: number, environmentName: string, testId: number, options?: any) {
        return SyntheticsApiFp(this.configuration).deleteTest(accountId, applicationId, environmentName, testId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Return all synthetics tests for an environment
     * @param {number} accountId The account identifier number
     * @param {number} applicationId The application identifier number
     * @param {string} environmentName The name of the environment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SyntheticsApi
     */
    public getTests(accountId: number, applicationId: number, environmentName: string, options?: any) {
        return SyntheticsApiFp(this.configuration).getTests(accountId, applicationId, environmentName, options).then((request) => request(this.axios, this.basePath));
    }
}
