/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    href?: any;
    /**
     * user defined account name
     * @type {string}
     * @memberof Account
     */
    account_name?: any;
    /**
     * does authenticated account have access to account
     * @type {boolean}
     * @memberof Account
     */
    is_admin?: any;
    /**
     * owner user id
     * @type {number}
     * @memberof Account
     */
    billing_user?: any;
    /**
     * All users on this account must log in with 2FA
     * @type {boolean}
     * @memberof Account
     */
    requires_2fa?: any;
    /**
     * 
     * @type {User}
     * @memberof Account
     */
    owner?: any;
}
