/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountUserInviteRequest
 */
export interface AccountUserInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountUserInviteRequest
     */
    first_name?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUserInviteRequest
     */
    last_name?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUserInviteRequest
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUserInviteRequest
     */
    phone_number?: any;
}
