/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountUser
 */
export interface AccountUser {
    /**
     * 
     * @type {number}
     * @memberof AccountUser
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    firstName?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    phoneNumber?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountUser
     */
    accountCapability?: any;
}
