/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountGraph
 */
export interface AccountGraph {
    /**
     * 
     * @type {number}
     * @memberof AccountGraph
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountGraph
     */
    href?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountGraph
     */
    account_name?: any;
    /**
     * 
     * @type {Array&lt;AccountGraphApplications&gt;}
     * @memberof AccountGraph
     */
    applications?: any;
}
