/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ApplicationStateUpdateRequest
 */
export interface ApplicationStateUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationStateUpdateRequest
     */
    proxy: ApplicationStateUpdateRequestProxyEnum;
    /**
     * 
     * @type {string}
     * @memberof ApplicationStateUpdateRequest
     */
    ban?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum ApplicationStateUpdateRequestProxyEnum {
    Varnish = 'varnish'
}

