/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Application
 */
export interface Application {
    /**
     * 
     * @type {number}
     * @memberof Application
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    href?: any;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    application_name?: any;
    /**
     * 
     * @type {string}
     * @memberof Application
     */
    path_prefix?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Application
     */
    path_prefixes?: any;
}
