/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ApplicationCreateRequest
 */
export interface ApplicationCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    hostname: any;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    origin?: any;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    stackName?: any;
}
