/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BillingSummary
 */
export interface BillingSummary {
    /**
     * Billing enabled
     * @type {boolean}
     * @memberof BillingSummary
     */
    enabled?: any;
    /**
     * Billing provisioning
     * @type {boolean}
     * @memberof BillingSummary
     */
    provisioning?: any;
    /**
     * Billing linked to user
     * @type {string}
     * @memberof BillingSummary
     */
    user?: any;
    /**
     * Meter type for account
     * @type {string}
     * @memberof BillingSummary
     */
    meterType?: any;
    /**
     * Account balance for period
     * @type {number}
     * @memberof BillingSummary
     */
    outstandingBalance?: any;
    /**
     * Next billing period starts
     * @type {string}
     * @memberof BillingSummary
     */
    periodNext?: any;
    /**
     * Billing period started
     * @type {string}
     * @memberof BillingSummary
     */
    periodStarted?: any;
    /**
     * Billing portal URL
     * @type {string}
     * @memberof BillingSummary
     */
    billingPortal?: any;
    /**
     * Account status
     * @type {string}
     * @memberof BillingSummary
     */
    state?: any;
}
