/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body3
 */
export interface Body3 {
    /**
     * Zone Name
     * @type {string}
     * @memberof Body3
     */
    zoneName: any;
    /**
     * Hostname
     * @type {string}
     * @memberof Body3
     */
    hostname?: any;
}
