/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body1
 */
export interface Body1 {
    /**
     * Record Name
     * @type {string}
     * @memberof Body1
     */
    recordName: any;
    /**
     * Record Type
     * @type {string}
     * @memberof Body1
     */
    recordType: any;
    /**
     * Original Record Type
     * @type {string}
     * @memberof Body1
     */
    originalRecordType?: any;
    /**
     * Time to live (seconds)
     * @type {number}
     * @memberof Body1
     */
    ttl: any;
    /**
     * Record Data
     * @type {Array&lt;any&gt;}
     * @memberof Body1
     */
    recordData: any;
}
