/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DomainListInner
 */
export interface DomainListInner {
    /**
     * 
     * @type {string}
     * @memberof DomainListInner
     */
    domainName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof DomainListInner
     */
    engaged?: any;
}
