/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DomainSummary
 */
export interface DomainSummary {
    /**
     * 
     * @type {string}
     * @memberof DomainSummary
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof DomainSummary
     */
    zoneName?: any;
    /**
     * 
     * @type {string}
     * @memberof DomainSummary
     */
    cname?: any;
    /**
     * 
     * @type {string}
     * @memberof DomainSummary
     */
    mode?: any;
}
