/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EgressOrigin
 */
export interface EgressOrigin {
    /**
     * 
     * @type {HostAddressDnsOrIp}
     * @memberof EgressOrigin
     */
    address: any;
    /**
     * 
     * @type {number}
     * @memberof EgressOrigin
     */
    http_port?: any;
    /**
     * 
     * @type {number}
     * @memberof EgressOrigin
     */
    https_port?: any;
    /**
     * 
     * @type {HostAddressDns}
     * @memberof EgressOrigin
     */
    host_header?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EgressOrigin
     */
    disable_keepalive?: any;
    /**
     * 
     * @type {number}
     * @memberof EgressOrigin
     */
    keepalive_seconds?: any;
    /**
     * 
     * @type {HostAddressDns}
     * @memberof EgressOrigin
     */
    tls_name?: any;
}
