/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EgressOrigin
 */
export interface EgressOrigin {
    /**
     * 
     * @type {HostAddressDnsOrIp}
     * @memberof EgressOrigin
     */
    address: any;
    /**
     * 
     * @type {number}
     * @memberof EgressOrigin
     */
    httpPort?: any;
    /**
     * 
     * @type {number}
     * @memberof EgressOrigin
     */
    httpsPort?: any;
    /**
     * 
     * @type {HostAddressDns}
     * @memberof EgressOrigin
     */
    hostHeader?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EgressOrigin
     */
    disableKeepalive?: any;
    /**
     * 
     * @type {number}
     * @memberof EgressOrigin
     */
    keepaliveSeconds?: any;
    /**
     * 
     * @type {HostAddressDns}
     * @memberof EgressOrigin
     */
    tlsName?: any;
}
