/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EnvironmentCreateRequest
 */
export interface EnvironmentCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentCreateRequest
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentCreateRequest
     */
    source_environment_name: any;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentCreateRequest
     */
    domain_name: any;
}
