/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EnvironmentSummary
 */
export interface EnvironmentSummary {
    /**
     * 
     * @type {number}
     * @memberof EnvironmentSummary
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentSummary
     */
    href?: any;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentSummary
     */
    environment_name?: any;
    /**
     * 
     * @type {Array&lt;DomainSummary&gt;}
     * @memberof EnvironmentSummary
     */
    domains?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EnvironmentSummary
     */
    is_hosted?: any;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentSummary
     */
    dns_bypass_address?: any;
}
