/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HttpsConfiguration
 */
export interface HttpsConfiguration {
    /**
     * 
     * @type {string}
     * @memberof HttpsConfiguration
     */
    type?: any;
    /**
     * 
     * @type {boolean}
     * @memberof HttpsConfiguration
     */
    configured?: any;
    /**
     * 
     * @type {string}
     * @memberof HttpsConfiguration
     */
    common_name?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof HttpsConfiguration
     */
    alternate_names?: any;
    /**
     * 
     * @type {string}
     * @memberof HttpsConfiguration
     */
    issuer?: any;
    /**
     * 
     * @type {string}
     * @memberof HttpsConfiguration
     */
    expires?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof HttpsConfiguration
     */
    certificates?: any;
    /**
     * 
     * @type {string}
     * @memberof HttpsConfiguration
     */
    hpkp_fingerprint?: any;
    /**
     * 
     * @type {boolean}
     * @memberof HttpsConfiguration
     */
    hostname_valid?: any;
}
