/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Origin
 */
export interface Origin {
    /**
     * Hostname
     * @type {string}
     * @memberof Origin
     */
    hostname?: any;
    /**
     * Hostname on a bare domain
     * @type {boolean}
     * @memberof Origin
     */
    hostname_bare?: any;
    /**
     * Hostname already exists on Section
     * @type {boolean}
     * @memberof Origin
     */
    hostname_duplicate?: any;
    /**
     * Origin detected
     * @type {boolean}
     * @memberof Origin
     */
    origin_detected?: any;
    /**
     * Detected origin endpoint
     * @type {string}
     * @memberof Origin
     */
    origin?: any;
    /**
     * Detected origin fixed endpoint
     * @type {boolean}
     * @memberof Origin
     */
    origin_fixed?: any;
    /**
     * Detected origin ip
     * @type {string}
     * @memberof Origin
     */
    origin_lookup?: any;
    /**
     * Origin multiple records
     * @type {boolean}
     * @memberof Origin
     */
    origin_multiple?: any;
    /**
     * Origin hint found
     * @type {string}
     * @memberof Origin
     */
    origin_hint?: any;
    /**
     * Thirdparty detected
     * @type {boolean}
     * @memberof Origin
     */
    thirdparty_detected?: any;
    /**
     * Thirdparty name
     * @type {string}
     * @memberof Origin
     */
    thirdparty_name?: any;
    /**
     * Detected application runnning on the origin
     * @type {string}
     * @memberof Origin
     */
    origin_app_name?: any;
}
