/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RFC6902Operation } from "./rfc6902-operation";

/**
 *
 * @export
 * @interface PatchRequest
 */
export interface PatchRequest extends Array<RFC6902Operation> {
}
