/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProxyConfiguration
 */
export interface ProxyConfiguration {
    /**
     * An identifier of the source system - used for making compatibility changes
     * @type {string}
     * @memberof ProxyConfiguration
     */
    personality?: any;
    /**
     * The configuration
     * @type {string}
     * @memberof ProxyConfiguration
     */
    content: any;
    /**
     * Message describing the configuration change
     * @type {string}
     * @memberof ProxyConfiguration
     */
    message?: any;
    /**
     * JSON blob containing features for this proxy
     * @type {string}
     * @memberof ProxyConfiguration
     */
    features?: any;
    /**
     * Content of the generated code
     * @type {string}
     * @memberof ProxyConfiguration
     */
    generatedContent?: any;
}
