/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Proxy
 */
export interface Proxy {
    /**
     * 
     * @type {string}
     * @memberof Proxy
     */
    href: any;
    /**
     * 
     * @type {string}
     * @memberof Proxy
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof Proxy
     */
    image: any;
    /**
     * 
     * @type {ProxyType}
     * @memberof Proxy
     */
    proxyType: any;
}
