/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * A JSONPatch document as defined by RFC 6902
 * @export
 * @interface RFC6902Operation
 */
export interface RFC6902Operation {
    /**
     * The operation to be performed
     * @type {string}
     * @memberof RFC6902Operation
     */
    op: RFC6902OperationOpEnum;
    /**
     * A JSON-Pointer
     * @type {string}
     * @memberof RFC6902Operation
     */
    path: any;
    /**
     * The value to be used within the operations.
     * @type {any}
     * @memberof RFC6902Operation
     */
    value?: any;
    /**
     * A string containing a JSON Pointer value.
     * @type {string}
     * @memberof RFC6902Operation
     */
    from?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum RFC6902OperationOpEnum {
    Add = 'add',
    Remove = 'remove',
    Replace = 'replace',
    Move = 'move',
    Copy = 'copy',
    Test = 'test'
}

