/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Stack
 */
export interface Stack {
    /**
     * 
     * @type {string}
     * @memberof Stack
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Stack
     */
    label?: any;
    /**
     * 
     * @type {string}
     * @memberof Stack
     */
    description?: any;
}
