/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Totp
 */
export interface Totp {
    /**
     * 
     * @type {string}
     * @memberof Totp
     */
    base32text?: any;
    /**
     * 
     * @type {string}
     * @memberof Totp
     */
    svg?: any;
    /**
     * 
     * @type {string}
     * @memberof Totp
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof Totp
     */
    pngDataUri?: any;
}
