/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ZoneSummary
 */
export interface ZoneSummary {
    /**
     * 
     * @type {string}
     * @memberof ZoneSummary
     */
    zone_name?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ZoneSummary
     */
    name_servers?: any;
}
