/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ZoneDetail
 */
export interface ZoneDetail {
    /**
     * 
     * @type {string}
     * @memberof ZoneDetail
     */
    zoneName?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ZoneDetail
     */
    nameServers?: any;
    /**
     * 
     * @type {Array&lt;ZoneRecord&gt;}
     * @memberof ZoneDetail
     */
    records?: any;
    /**
     * 
     * @type {{ [key, string]: Array&lt;any&gt;;}}
     * @memberof ZoneDetail
     */
    environments?: any;
}
