/* tslint:disable */
/* eslint-disable */
/**
 * Section API
 * Get edgey with the Section API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ZoneRecord
 */
export interface ZoneRecord {
    /**
     * 
     * @type {string}
     * @memberof ZoneRecord
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof ZoneRecord
     */
    ttl?: any;
    /**
     * 
     * @type {string}
     * @memberof ZoneRecord
     */
    record_type?: any;
    /**
     * 
     * @type {Array}
     * @memberof ZoneRecord
     */
    record_data?: any;
}
